name: backend-ci

on:
  pull_request:
    branches:
      - main

env:
  PYTHON_VER: 3.12
  IMAGE_REPO_BE: backend

jobs:
  lint:
    name: Run lint for backend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./starter/backend
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3
      
      - name: Setup python environment
        uses: actions/setup-python@v4
        with:
          python-version: ${{env.PYTHON_VER}}
      
      - name: Install pipenv
        run: |
          pip install pipenv
          pip install flake8
      
      - name: Install dependencies package
        run: |
          pipenv install
      
      - name: Run lint
        run: |
          pipenv run lint

  test:
    name: Run test for backend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./starter/backend
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3
      
      - name: Setup python environment
        uses: actions/setup-python@v4
        with:
          python-version: ${{env.PYTHON_VER}}
      
      - name: Install pipenv
        run: |
          pip install pipenv
          pip install flake8
      
      - name: Install dependencies package
        run: |
          pipenv install
      
      - name: Run lint
        run: |
          pipenv run test
          
  build: 
    name: Build docker image for backend
    runs-on: ubuntu-latest
    needs: [lint, test]
    defaults:
      run:
        working-directory: ./starter/backend
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3
      
      - name: Build docker image for backend
        run: |
          docker build -t ${{env.IMAGE_REPO_BE}} .

                    