name: frontend-ci

on:
  pull_request:
    branches:
      - main

env:
  NODE_VER: 14

jobs:
  lint:
    name: Run lint frontend
    defaults:
      run:
        working-directory: ./starter/frontend
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Setup Nodejs environment
        uses: actions/setup-node@v3
        with:
          node-version: ${{env.NODE_VER}}

      - name: Install dependencies
        run: |
          npm install
        
      - name: Run lint
        run: |
          npm run lint