name: frontend-cd

on:
  pull_request:
    branches:
      - main

env:
  NODE_VER: 14

jobs:
  run-lint-test:
    name: Run lint frontend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./starter/frontend
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Setup Nodejs env
        uses: actions/setup-node@v3
        with:
          node-version: ${{env.NODE_VER}}

      - name: Cache dependencies
        id: cache
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies package prettier
        run: |
          npm install
          npm install prettier@2.8.8 --save-dev
        
      - name: Run lint
        run: |
          npm run lint
          npm run test
  deploy-to-ecr:
    name: Build, tag and push docker image to AWS ECR
    runs-on: ubuntu-latest
    needs: [run-lint-test]
    defaults:
      run:
        working-directory: ./starter/frontend
    steps:
      - name: Checkout repository code
        run: echo "Checkout repository code"
        uses: actions/checkout@v3
      
      - name: Configure AWS credential
        run: echo "Configure AWS credential"
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws-session-token: ${{secrets.AWS_SESSION_TOKEN}}
          aws-region: us-east-1